[package]
name = "Nm-otool"
version = "0.1.0"
authors = ["Baptiste Fraikin <ba.fraikin@gmail.com>", "Arman Dejbakhsh <arman@dejbakhsh.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
